sky:
  datasource:
    host: localhost
    port: 3306
    database: sky_take_out
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ddd123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ${SKY_ALIOSS_ACCESS_KEY_ID}
    access-key-secret: ${SKY_ALIOSS_ACCESS_KEY_SECRET}
    bucketName: java-ai1114
  redis:
    host: localhost
    port: 6379
    password: ddd123456
    database: 10
  wechat:
    appid: wx183d15cf27aa42da
    secret: 2a86814b9571d4848755d7c7e0b422ea
